// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Post struct {
	ID        string         `db:"id" json:"id"`
	AuthorID  string         `db:"author_id" json:"author_id"`
	Body      sql.NullString `db:"body" json:"body"`
	CreatedAt string         `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullString `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID        string         `db:"id" json:"id"`
	Email     sql.NullString `db:"email" json:"email"`
	Name      sql.NullString `db:"name" json:"name"`
	Username  string         `db:"username" json:"username"`
	Bio       sql.NullString `db:"bio" json:"bio"`
	Password  sql.NullString `db:"password" json:"password"`
	AvatarUrl sql.NullString `db:"avatar_url" json:"avatar_url"`
	CreatedAt string         `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullString `db:"updated_at" json:"updated_at"`
}
